name: Crypto News

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # jalan tiap 6 jam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run script
        env:
          CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
        run: python trending.py

      - name: Commit results
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add TRENDING.md
          git commit -m "Update trending news" || exit 0
          git push
