name: Crypto News

on:
  schedule:
    - cron: "0 */12 * * *"   # jalan tiap 12 jam
  workflow_dispatch:         # bisa jalan manual juga

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Run script
        env:
          CRYPTOPANIC_API_KEY: ${{ secrets.CRYPTOPANIC_API_KEY }}
        run: python trending.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add TRENDING.md
          git commit -m "Update trending news" || echo "No changes to commit"
          git push
