name: Crypto Trends

on:
  workflow_dispatch: # bisa dijalankan manual
  schedule:
    - cron: "0 2 * * *" # otomatis tiap hari jam 09:00 WIB (02:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          SENTIMENT_API_KEY: ${{ secrets.SENTIMENT_API_KEY }}
        run: python trending.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add TRENDING.md
          git commit -m "Update trending data" || echo "No changes to commit"
          git push
