name: Update KOL narratives & trending coins

on:
  schedule:
    - cron: "0 * * * *"  # jalan tiap 1 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests pytz

      - name: Run script
        run: python kol_narratives.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add KOL_TRENDING.md
          git commit -m "Update KOL narratives & trending coins"
          git push
